
import { JetBrains_Mono } from "next/font/google";
import "./globals.css";
import Header from "../components/Header";
import PageTransition from "../components/PageTransition";
import StairTransition from '../components/StairTransition'

import Footer from '../components/Footer'
import { Providers } from "./provider";
import AppProvider from "../AppContext.js"
import React from "react";
import { getSession } from "@/actions/getUser";

const jetBrainsMono = JetBrains_Mono({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800"],
  variable: "--font-jetbrainsMono"
});


export const metadata = {
  title: "Amro Elmutasim",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }: { children: React.ReactNode}) {

  const session = await getSession();
  console.log(session?.user?.email)

  return (
    <html lang="en">
      <head>
      <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css"></link>
      {/* <script src="https://unpkg.com/@tailwindcss/browser@4"></script> */}
      </head>

      <body
        className={`${jetBrainsMono.variable} flex flex-col justify-center xl:max-w-[85%] mx-auto mb-12 max-xl:mt-4`}
      >
        <AppProvider session>
          <Providers>
            
          <Header email={session?.user?.email} />
        
        <PageTransition>{children}</PageTransition>

        <Footer />

          </Providers>
        </AppProvider>

        
        
      </body>
    </html>
  );
}
