
import { JetBrains_Mono } from "next/font/google";
import "./globals.css";
import Header from "../../components/Header";
import PageTransition from "../../components/PageTransition";
import StairTransition from '../../components/StairTransition'

import Footer from '../../components/Footer'
import { Providers } from "./provider";
import AppProvider from "../../AppContext.js"
import React from "react";
import { getSession } from "@/actions/getUser";
import { NextIntlClientProvider } from "next-intl";
import { getMessages } from "next-intl/server";
import {notFound} from 'next/navigation';
import {routing} from '@/i18n/routing';
import styles from "./layout.module.css"; 



const jetBrainsMono = JetBrains_Mono({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800"],
  variable: "--font-jetbrainsMono"
});


export const metadata = {
  title: "Amro Elmutasim",
  description: "Generated by create next app",
};

export default async function RootLayout({ children, params: { locale } }: {
  children: React.ReactNode,
  params: { locale: string }
}) {

  if (!routing.locales.includes(locale as any)) {
    notFound();
  }

  const session = await getSession();
  console.log(session?.user?.email)

  const messages = await getMessages();

  return (
    <html lang={locale} dir={locale === 'ar' ? 'rtl' : 'ltr'}>
      <head>
      <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css"></link>
      {/* <script src="https://unpkg.com/@tailwindcss/browser@4"></script> */}

      
      </head>

      <body
        className={`${jetBrainsMono.variable} flex flex-col justify-center xl:max-w-[85%] mx-auto mb-12 max-xl:mt-4
        overflow-x-hidden
        ${locale === 'ar' ? styles.arabic : styles.english}`}
        
      >
        

        <NextIntlClientProvider messages={messages}>
        <AppProvider session>
          <Providers>
            
          <Header email={session?.user?.email} locale={locale} />
        
        <PageTransition>{children}</PageTransition>

        <Footer email={session?.user?.email} />

          </Providers>
        </AppProvider>
        </NextIntlClientProvider>

        
        
      </body>
    </html>
  );
}
